global using System;
global using System.Collections.Generic;
global using System.Collections.Concurrent;
global using System.Linq;
global using System.Threading.Tasks;
global using RabbitMQ.Client;
global using RabbitMQ.Client.Events;
global using Zaabee.RabbitMQ.Abstractions;
global using Zaabee.Serializer.Abstractions;